import type { ToolPreparationSpec } from "./types.js";

type SharedPreparation = Omit<ToolPreparationSpec, "toolName">;

function rows(toolNames: readonly string[], shared: SharedPreparation): ToolPreparationSpec[] {
  return toolNames.map((toolName) => Object.freeze({
    toolName,
    currentSource: shared.currentSource,
    effectClass: shared.effectClass,
    replay: shared.replay,
    contextFields: Object.freeze([...shared.contextFields]),
    serviceEffector: shared.serviceEffector,
    abortExpectation: shared.abortExpectation,
    protectedFields: Object.freeze([...shared.protectedFields]),
  }));
}

const source = {
  core: "@earendil-works/pi-coding-agent core tools; runtime/src/agent-pool/tool-factory.ts; runtime/src/extensions/ssh-core.ts",
  effectiveSearch: "@earendil-works/pi-coding-agent read-only tool definitions; effective Piclaw execution surface advertised by runtime/src/extensions/ssh.ts; no branch-local direct constructor",
  context: "runtime/extensions/integrations/context-mode.ts; runtime/src/tools/context-tools.ts",
  activation: "runtime/src/extensions/tool-activation.ts",
  attachments: "runtime/src/extensions/file-attachments.ts",
  models: "runtime/src/extensions/model-control.ts",
  scheduling: "runtime/src/extensions/scheduled-tasks.ts",
  workspace: "runtime/src/extensions/workspace-search.ts",
  contextPrune: "runtime/src/extensions/context-prune.ts; runtime/src/extensions/context-prune/query-tool.ts",
} as const;

/**
 * Exact repository-owned tool families. This inert manifest is not imported by
 * tool registration or session composition.
 */
export const TOOL_PREPARATION_MANIFEST: readonly ToolPreparationSpec[] = Object.freeze([
  ...rows(["read"], {
    currentSource: source.core,
    effectClass: "query",
    replay: "safe",
    contextFields: ["env"],
    serviceEffector: null,
    abortExpectation: "must_stop",
    protectedFields: ["params.path", "result.content"],
  }),
  ...rows(["write"], {
    currentSource: source.core,
    effectClass: "mutation",
    replay: "never",
    contextFields: ["env"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.path", "params.content"],
  }),
  ...rows(["edit"], {
    currentSource: source.core,
    effectClass: "mutation",
    replay: "never",
    contextFields: ["env"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.path", "params.edits", "params.oldText", "params.newText"],
  }),
  ...rows(["bash"], {
    currentSource: source.core,
    effectClass: "mutation",
    replay: "never",
    contextFields: ["env"],
    serviceEffector: null,
    abortExpectation: "must_stop",
    protectedFields: ["params.command", "result.content", "result.details.fullOutputPath"],
  }),
  ...rows(["grep", "find", "ls"], {
    currentSource: source.effectiveSearch,
    effectClass: "query",
    replay: "safe",
    contextFields: ["env"],
    serviceEffector: null,
    abortExpectation: "must_stop",
    protectedFields: ["params.path", "params.pattern", "result.content"],
  }),
  ...rows(["local_bash"], {
    currentSource: "runtime/src/extensions/ssh-core.ts",
    effectClass: "mutation",
    replay: "never",
    contextFields: ["localEnv"],
    serviceEffector: null,
    abortExpectation: "must_stop",
    protectedFields: ["params.command", "result.content", "result.details.fullOutputPath"],
  }),
  ...rows(["powershell"], {
    currentSource: "runtime/extensions/platform/windows/powershell/index.ts (win32 gate)",
    effectClass: "mutation",
    replay: "never",
    contextFields: ["env"],
    serviceEffector: null,
    abortExpectation: "must_stop",
    protectedFields: ["params.command", "result.content", "result.details.fullOutputPath"],
  }),
  ...rows(["exec_batch"], {
    currentSource: source.context,
    effectClass: "mutation",
    replay: "never",
    contextFields: ["env"],
    serviceEffector: null,
    abortExpectation: "must_stop",
    protectedFields: ["params.commands", "result.content", "result.details.fullOutputPath"],
  }),
  ...rows(["search_tool_output"], {
    currentSource: source.context,
    effectClass: "query",
    replay: "safe",
    contextFields: ["localEnv"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.handle", "params.query", "result.content"],
  }),
  ...rows(["list_tools"], {
    currentSource: "runtime/src/extensions/internal-tools.ts",
    effectClass: "query",
    replay: "safe",
    contextFields: [],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.query", "params.intent"],
  }),
  ...rows(["list_scripts"], {
    currentSource: "runtime/src/extensions/runtime-scripts.ts",
    effectClass: "query",
    replay: "safe",
    contextFields: [],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.query", "params.intent", "result.content"],
  }),
  ...rows(["activate_tools", "reset_active_tools"], {
    currentSource: source.activation,
    effectClass: "mutation",
    replay: "never",
    contextFields: [],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: [],
  }),
  ...rows(["attach_file"], {
    currentSource: source.attachments,
    effectClass: "mutation",
    replay: "never",
    contextFields: ["chatJid", "operationId", "localEnv"],
    serviceEffector: "EF-S04",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.path", "params.name", "result.content", "result.details"],
  }),
  ...rows(["read_attachment"], {
    currentSource: source.attachments,
    effectClass: "query",
    replay: "safe",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: "EF-S04",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.id", "result.content", "result.details"],
  }),
  ...rows(["export_attachment"], {
    currentSource: source.attachments,
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId", "localEnv"],
    serviceEffector: "EF-S04",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.id", "params.filename", "result.content", "result.details"],
  }),
  ...rows(["messages"], {
    currentSource: "runtime/src/extensions/messages-crud.ts",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.chat_jid", "params.target_chat_jid", "params.row_ids", "params.sender", "params.content", "params.content_blocks", "params.content_grep", "params.media_ids", "params.pattern", "params.query", "result.content", "result.details"],
  }),
  ...rows(["get_model_state"], {
    currentSource: source.models,
    effectClass: "query",
    replay: "safe",
    contextFields: [],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: [],
  }),
  ...rows(["list_models"], {
    currentSource: source.models,
    effectClass: "query",
    replay: "safe",
    contextFields: [],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.query"],
  }),
  ...rows(["switch_model", "switch_thinking"], {
    currentSource: source.models,
    effectClass: "mutation",
    replay: "never",
    contextFields: [],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: [],
  }),
  ...rows(["introspect_sql"], {
    currentSource: "runtime/src/extensions/sql-introspect.ts",
    effectClass: "query",
    replay: "safe",
    contextFields: ["chatJid"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.query", "result.content", "result.details"],
  }),
  ...rows(["schedule_task"], {
    currentSource: source.scheduling,
    effectClass: "mutation",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: "EF-S07",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.chat_jid", "params.prompt", "params.command", "params.cwd", "result.content", "result.details"],
  }),
  ...rows(["scheduled_tasks"], {
    currentSource: source.scheduling,
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: "EF-S07",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.id", "params.chat_jid", "params.prompt", "params.command", "params.cwd", "result.content", "result.details"],
  }),
  ...rows(["search_workspace"], {
    currentSource: source.workspace,
    effectClass: "query",
    replay: "safe",
    contextFields: ["localEnv"],
    serviceEffector: null,
    abortExpectation: "must_stop",
    protectedFields: ["params.query", "result.content"],
  }),
  ...rows(["refresh_workspace_index"], {
    currentSource: source.workspace,
    effectClass: "mutation",
    replay: "never",
    contextFields: ["operationId", "localEnv"],
    serviceEffector: "EF-S05",
    abortExpectation: "may_finish_late",
    protectedFields: ["result.content", "result.details"],
  }),
  ...rows(["send_adaptive_card", "send_dashboard_widget"], {
    currentSource: "runtime/src/extensions/send-adaptive-card.ts; runtime/src/extensions/send-dashboard-widget.ts",
    effectClass: "mutation",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: "EF-S03",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.card", "params.html", "params.content", "params.card_id", "params.payload", "params.chat_jid", "params.fallback_text", "params.state", "params.last_submission", "params.title", "params.open_label", "params.widget_id", "result.content", "result.details"],
  }),
  ...rows(["chat"], {
    currentSource: "runtime/src/extensions/chat-tool.ts",
    effectClass: "mutation",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: "EF-S01",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.action", "params.content", "params.files", "params.target_address", "params.target_chat_jid", "params.target_agent_name", "params.media_ids", "params.idempotency_key", "params.in_reply_to", "result.content", "result.details"],
  }),
  ...rows(["session_control"], {
    currentSource: "runtime/src/extensions/session-control.ts",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: "EF-S01",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.target_address", "params.target_chat_jid", "params.target_agent_name", "params.instructions", "result.content", "result.details"],
  }),
  ...rows(["session_status"], {
    currentSource: "runtime/src/extensions/session-status.ts",
    effectClass: "query",
    replay: "safe",
    contextFields: ["chatJid"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["result.details"],
  }),
  ...rows(["open_workspace_file"], {
    currentSource: "runtime/src/extensions/open-workspace-file.ts",
    effectClass: "mutation",
    replay: "never",
    contextFields: ["chatJid", "operationId", "localEnv"],
    serviceEffector: "EF-S05",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.path", "params.label"],
  }),
  ...rows(["env"], {
    currentSource: "runtime/src/extensions/env-tools.ts",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["localEnv"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.name", "params.value", "result.content", "result.details"],
  }),
  ...rows(["exit_process"], {
    currentSource: "runtime/src/extensions/exit-process.ts",
    effectClass: "mutation",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: "EF-S05",
    abortExpectation: "may_finish_late",
    protectedFields: ["params.reason", "params.resume_message"],
  }),
  ...rows(["image_process"], {
    currentSource: "runtime/src/extensions/image-processing.ts",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["localEnv"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.input", "params.output", "params.overlay", "params.text", "result.content", "result.details"],
  }),
  ...rows(["context_prune"], {
    currentSource: source.contextPrune,
    effectClass: "mutation",
    replay: "never",
    contextFields: [],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["result.content", "result.details"],
  }),
  ...rows(["context_tree_query"], {
    currentSource: source.contextPrune,
    effectClass: "query",
    replay: "safe",
    contextFields: [],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.toolCallIds", "result.content", "result.details"],
  }),
  ...rows(["bun_run"], {
    currentSource: "runtime/extensions/integrations/bun-runner/index.ts; runtime/src/extensions/bun-runner.ts",
    effectClass: "mutation",
    replay: "never",
    contextFields: ["env"],
    serviceEffector: null,
    abortExpectation: "must_stop",
    protectedFields: ["params.script", "params.args", "params.cwd", "result.content", "result.details"],
  }),
  ...rows(["keychain"], {
    currentSource: "runtime/extensions/integrations/keychain/index.ts; runtime/src/extensions/keychain-tools.ts",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.name", "params.secret", "params.username", "result.content", "result.details"],
  }),
  ...rows(["ssh"], {
    currentSource: "runtime/extensions/integrations/ssh/index.ts; runtime/src/extensions/ssh.ts; runtime/src/extensions/ssh-core.ts",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.chat_jid", "params.ssh_target", "params.private_key_keychain", "params.known_hosts_keychain", "result.content", "result.details"],
  }),
  ...rows(["cdp_browser"], {
    currentSource: "runtime/extensions/browser/cdp-browser-tool/index.ts production registration; runtime/extensions/browser/cdp-browser/index.ts execution module",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["localEnv"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.expr", "params.url", "params.match", "params.selector", "params.outPath", "params.headerTemplate", "params.footerTemplate", "result.content", "result.details"],
  }),
  ...rows(["mcp"], {
    currentSource: "runtime/src/agent-pool/session.ts createMcpAdapter composition; package.json pi-mcp-adapter dependency",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId", "localEnv"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.tool", "params.args", "params.server", "params.search", "params.describe", "params.instructions", "params.connect", "params.redirectUrl", "result.content", "result.details"],
  }),
]);

/**
 * Conservative templates for tool names not owned by this repository. A
 * template never satisfies exact-name coverage and never authorises activation.
 */
export const DYNAMIC_TOOL_PREPARATION_TEMPLATES: readonly ToolPreparationSpec[] = Object.freeze([
  ...rows(["<addon-tool>"], {
    currentSource: "add-on package path declared by pi.extensions; WP-3C resolves only hermetic package fixtures",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId", "env", "localEnv"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.*", "result.*"],
  }),
  ...rows(["<mcp-direct-tool>"], {
    currentSource: "pi-mcp-adapter cached server metadata after directTools/includeTools/excludeTools and prefix normalization; WP-3C uses hermetic metadata fixtures",
    effectClass: "mixed",
    replay: "never",
    contextFields: ["chatJid", "operationId", "env", "localEnv"],
    serviceEffector: null,
    abortExpectation: "may_finish_late",
    protectedFields: ["params.*", "result.*"],
  }),
]);

/** Future direct harness targets; currentSource above remains the released coding-agent wiring. */
export const CORE_EARENDIL_FACTORY_TARGETS = Object.freeze({
  package: "@earendil-works/pi-agent-core",
  exports: Object.freeze({
    read: "createReadTool",
    write: "createWriteTool",
    edit: "createEditTool",
    bash: "createBashTool",
  }),
} as const);

export const MESSAGES_ACTIVATION_BLOCKER = [
  "messages remains mixed/never with null service effector.",
  "add/post are future EF-S03 candidates, but delete/move target arbitrary history and have no closed EF-S03 authority.",
  "Future activation requires a separately approved fenced administrative timeline contract or retirement of delete/move.",
].join(" ");
