import {afterEach,beforeEach,expect,test} from 'bun:test';
import Database from 'bun:sqlite';import {mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {createTempWorkspace,setEnv} from '../helpers.js';
import {closeDatabase,getDb,initDatabase} from '../../src/db/connection.js';
import {createWebSession} from '../../src/db/web-sessions.js';
import {getUser} from '../../src/db/users.js';
import {provisionFamilyAccount,updateManagedAccount} from '../../src/db/account-administration.js';
import {resolveRequestPrincipal} from '../../src/channels/web/auth/principal.js';
import {issueOperatorRecovery} from '../../src/secure/operator-recovery.js';
import {createOperatorRecoveryRequestHandler,serveOperatorRecovery} from '../../src/secure/operator-recovery-server.js';import {parseOperatorRecoveryArgs} from '../../src/cli-operator-recovery.js';
import {acquireRuntimeLock} from '../../src/runtime/single-instance.js';
import {createHmac} from 'node:crypto';import {invitationKey,invitationProof} from './passkey-fixture.js';

const origin='https://family.local';let ws:ReturnType<typeof createTempWorkspace>,restore:()=>void,id:string,recoveryId:string,token:string;
beforeEach(()=>{ws=createTempWorkspace('operator-recovery-server-');restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data,PICLAW_KEYCHAIN_KEY:'test-recovery-key'});mkdirSync(join(ws.workspace,'.piclaw'));writeFileSync(join(ws.workspace,'.piclaw/config.json'),JSON.stringify({domains:{access:{mode:'family-shared'}}}));closeDatabase();initDatabase();const db=getDb(),login=createWebSession('admin','default',3600,'passkey'),actor=resolveRequestPrincipal(new Request(origin,{headers:{cookie:'piclaw_session=x'}}),{mode:'family-shared',authEnabled:true},{getSession:()=>login,getUser:()=>getUser(db,'default'),getLocalDisplayName:()=>''})!;id=provisionFamilyAccount(db,actor,{username:'alice',displayName:'Alice',role:'admin'}).id;db.query("INSERT INTO webauthn_credentials(user_id,rp_id,credential_id,public_key) VALUES (?,'family.local','lost','key')").run(id);updateManagedAccount(db,actor,id,{enabled:true},{totp:false,passkey:true,rpId:'family.local'});db.query("UPDATE users SET enabled=0 WHERE id='default'").run();db.query("UPDATE access_state SET activated_mode='family-shared'").run();let grant!:any;const issued=issueOperatorRecovery(db,{userId:id,username:'alice',method:'passkey',origin},value=>{grant=value;});recoveryId=issued.recovery_id;token=new URLSearchParams(new URL(grant.url).hash.slice(1)).get('token')!;});
afterEach(()=>{closeDatabase();restore();ws.cleanup();});
const request=(path:string,body?:unknown,headers:Record<string,string>={})=>new Request(origin+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{origin,'content-type':'application/json'}),...headers},body:body===undefined?undefined:JSON.stringify(body)});
function code(secret:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,buffer=0;const bytes:number[]=[];for(const c of secret){buffer=(buffer<<5)|alphabet.indexOf(c);bits+=5;if(bits>=8){bits-=8;bytes.push((buffer>>bits)&255);}}const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30_000)));const h=createHmac('sha1',Buffer.from(bytes)).update(counter).digest();return(h.readUInt32BE(h[h.length-1]!&15)%0x80000000%1_000_000).toString().padStart(6,'0');}

test('recovery handler exposes only pinned invitation assets and denies ordinary runtime routes',async()=>{const handler=createOperatorRecoveryRequestHandler(getDb(),{recoveryId,origin});for(const path of ['/','/login','/auth/options','/auth/me','/sse/stream','/api/addons/test','/static/common/dist/family.bundle.js','/auth/invitation?x=1'])expect((await handler(request(path))).status).toBe(404);expect((await handler(request('/auth/invitation'))).status).toBe(200);expect((await handler(request('/static/common/dist/login.bundle.css'))).status).toBe(200);expect((await handler(request('/static/common/dist/invitation.bundle.js'))).status).toBe(200);});

test('recovery handler pins event and origin and rejects unbounded or non-JSON claims',async()=>{const fake='operator-recovery-00000000-0000-4000-8000-000000000000';expect((await createOperatorRecoveryRequestHandler(getDb(),{recoveryId:fake,origin})(request('/auth/invitation'))).status).toBe(404);const handler=createOperatorRecoveryRequestHandler(getDb(),{recoveryId,origin});expect((await handler(new Request('https://evil.local/auth/invitation'))).status).toBe(404);expect((await handler(request('/auth/invitation/passkey/claim',{token},{'content-type':'text/plain'}))).status).toBe(403);expect((await handler(new Request(origin+'/auth/invitation/passkey/claim',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({token,padding:'x'.repeat(70_000)})}))).status).toBe(403);});

test('recovery-only scope rejects ordinary invitations, changed grants and expired events',async()=>{const db=getDb(),handler=createOperatorRecoveryRequestHandler(db,{recoveryId,origin});db.query('UPDATE user_auth_invitations SET recovery_event_id=NULL,expected_origin=NULL').run();expect((await handler(request('/auth/invitation/passkey/claim',{token}))).status).toBe(404);db.query('UPDATE user_auth_invitations SET recovery_event_id=?,expected_origin=?').run(recoveryId,origin);db.query('UPDATE operator_recovery_events SET created_at=? WHERE id=?').run(new Date(Date.now()-16*60_000).toISOString(),recoveryId);expect((await handler(request('/auth/invitation'))).status).toBe(404);});

test('serve CLI parser requires exact recovery id confirmation and preserves exact origin',()=>{const args=['serve','--recovery-id',recoveryId,'--origin',origin,'--writers-stopped','--confirm',`SERVE RECOVERY ${recoveryId}`];expect(parseOperatorRecoveryArgs(args)).toEqual({action:'serve',apply:false,recoveryId,origin});for(const invalid of [args.filter(v=>v!=='--writers-stopped'),args.map(v=>v===`SERVE RECOVERY ${recoveryId}`?'wrong':v),[...args,'--output','secret']])expect(()=>parseOperatorRecoveryArgs(invalid)).toThrow();});

test('successful passkey recovery signals completion without issuing a login',async()=>{let completed=0;const handler=createOperatorRecoveryRequestHandler(getDb(),{recoveryId,origin},()=>completed++);const claimed=await handler(request('/auth/invitation/passkey/claim',{token})),claim=await claimed.json();expect(claimed.status).toBe(200);const key=invitationKey('recovery-server');const confirmed=await handler(request('/auth/invitation/passkey/confirm',{token,enrolment_token:claim.enrolment_token,credential:invitationProof(key,claim.options.challenge)} ,{cookie:claimed.headers.get('set-cookie')!.split(';')[0]!}));expect(await confirmed.json()).toEqual({enrolled:true,login_required:true,recovery_only:true});expect(completed).toBe(1);expect(getUser(getDb(),id)?.enabled).toBe(true);expect(getDb().query('SELECT * FROM web_sessions WHERE user_id=?').all(id)).toEqual([]);expect(confirmed.headers.get('set-cookie')).not.toContain('piclaw_session');expect((await handler(request('/auth/invitation'))).status).toBe(404);});

test('recovery event drift during passkey verification denies completion',async()=>{const db=getDb(),handler=createOperatorRecoveryRequestHandler(db,{recoveryId,origin}),claimed=await handler(request('/auth/invitation/passkey/claim',{token})),claim=await claimed.json(),pending=handler(request('/auth/invitation/passkey/confirm',{token,enrolment_token:claim.enrolment_token,credential:invitationProof(invitationKey('recovery-race'),claim.options.challenge)},{cookie:claimed.headers.get('set-cookie')!.split(';')[0]!}));db.query('UPDATE operator_recovery_events SET origin=? WHERE id=?').run('https://changed.invalid',recoveryId);expect((await pending).status).toBe(403);expect(getUser(db,id)?.enabled).toBe(false);expect(db.query('SELECT * FROM webauthn_credentials WHERE user_id=?').all(id)).toEqual([]);});

test('successful TOTP recovery revalidates the scoped event after factor insertion',async()=>{const db=getDb();db.query('DELETE FROM user_auth_invitations; DELETE FROM operator_recovery_events').run();db.query("UPDATE users SET enabled=1 WHERE id=?").run(id);let grant!:any;const issued=issueOperatorRecovery(db,{userId:id,username:'alice',method:'totp',origin},value=>{grant=value;});const recovery=issued.recovery_id,recoveryToken=new URLSearchParams(new URL(grant.url).hash.slice(1)).get('token')!;let completed=0;const handler=createOperatorRecoveryRequestHandler(db,{recoveryId:recovery,origin},()=>completed++),claimed=await handler(request('/auth/invitation/claim',{token:recoveryToken})),claim=await claimed.json();expect(claimed.status).toBe(200);const confirmed=await handler(request('/auth/invitation/confirm',{token:recoveryToken,enrolment_token:claim.enrolment_token,code:code(claim.secret)},{cookie:claimed.headers.get('set-cookie')!.split(';')[0]!}));expect(await confirmed.json()).toEqual({enrolled:true,login_required:true,recovery_only:true});expect(completed).toBe(1);expect(getUser(db,id)?.enabled).toBe(true);expect(db.query('SELECT count(*) n FROM user_totp_factors WHERE user_id=?').get(id)).toEqual({n:1});});

test('TOTP recovery listener refuses startup without encryption key material',async()=>{const db=getDb();db.query('DELETE FROM user_auth_invitations; DELETE FROM operator_recovery_events').run();db.query("UPDATE users SET enabled=1 WHERE id=?").run(id);let grant!:any;const issued=issueOperatorRecovery(db,{userId:id,username:'alice',method:'totp',origin},value=>{grant=value;});const previous=process.env.PICLAW_KEYCHAIN_KEY;delete process.env.PICLAW_KEYCHAIN_KEY;try{await expect(serveOperatorRecovery({recoveryId:issued.recovery_id,origin},{database:db,serverConfig:{host:'127.0.0.1',port:9443,idleTimeout:0,tlsCert:'unused',tlsKey:'unused'},serve:(()=>{throw new Error('must not listen');}) as typeof Bun.serve})).rejects.toThrow('bootstrap key');}finally{if(previous===undefined)delete process.env.PICLAW_KEYCHAIN_KEY;else process.env.PICLAW_KEYCHAIN_KEY=previous;}});

test('standalone server opens the existing store without migrations, holds its lock and stops after recovery',async()=>{const cert=join(ws.workspace,'cert.pem'),key=join(ws.workspace,'key.pem'),source=join(ws.store,'messages.db'),db=getDb();writeFileSync(cert,'CERT');writeFileSync(key,'KEY');const schema=JSON.stringify(db.query("SELECT type,name,tbl_name,sql FROM sqlite_master ORDER BY type,name").all());db.query('VACUUM INTO ?').run(source);closeDatabase();let fetch!:(req:Request)=>Promise<Response>,stops=0;const running=serveOperatorRecovery({recoveryId,origin},{serverConfig:{host:'127.0.0.1',port:9443,idleTimeout:0,tlsCert:cert,tlsKey:key},serve:((options:any)=>{expect(options.maxRequestBodySize).toBe(64*1024);expect(options.tls).toEqual({cert:'CERT',key:'KEY'});fetch=options.fetch;return{stop:()=>{stops++;}};}) as typeof Bun.serve});await Bun.sleep(5);expect(fetch).toBeDefined();expect(()=>acquireRuntimeLock({lockPath:join(ws.store,'runtime.lock'),maintenance:true,disabled:false})).toThrow('already running');const claimed=await fetch(request('/auth/invitation/passkey/claim',{token})),claim=await claimed.json();const keyPair=invitationKey('recovery-listener');await fetch(request('/auth/invitation/passkey/confirm',{token,enrolment_token:claim.enrolment_token,credential:invitationProof(keyPair,claim.options.challenge)},{cookie:claimed.headers.get('set-cookie')!.split(';')[0]!}));await running;expect(stops).toBeGreaterThan(0);const reopened=new Database(source,{readonly:true});try{expect(getUser(reopened,id)?.enabled).toBe(true);expect(JSON.stringify(reopened.query("SELECT type,name,tbl_name,sql FROM sqlite_master ORDER BY type,name").all())).toBe(schema);}finally{reopened.close();}});

test('standalone listener stops when the scoped grant expires and releases its lock',async()=>{const cert=join(ws.workspace,'cert.pem'),key=join(ws.workspace,'key.pem'),db=getDb();writeFileSync(cert,'CERT');writeFileSync(key,'KEY');db.query('UPDATE user_auth_invitations SET expires_at=?').run(Date.now()+25);let stops=0;await serveOperatorRecovery({recoveryId,origin},{database:db,serverConfig:{host:'127.0.0.1',port:9443,idleTimeout:0,tlsCert:cert,tlsKey:key},serve:(()=>({stop:()=>{stops++;}})) as typeof Bun.serve});expect(stops).toBeGreaterThan(0);const lock=acquireRuntimeLock({lockPath:join(ws.store,'runtime.lock'),maintenance:true,disabled:false});lock.release();});
