import { AUTO_DREAM_DEFAULT_DAYS, MANUAL_DREAM_DEFAULT_DAYS } from "../dream-defaults.js";

export function buildDreamPrompt(options?: { mode?: "manual" | "auto"; days?: number }): string {
  const mode = options?.mode === "auto" ? "auto" : "manual";
  const days = Number.isFinite(options?.days) && Number(options?.days) > 0
    ? Math.floor(Number(options?.days))
    : (mode === "auto" ? AUTO_DREAM_DEFAULT_DAYS : MANUAL_DREAM_DEFAULT_DAYS);

  return [
    mode === "auto" ? `auto dream ${days}` : `dream ${days}`,
    "",
    "Perform Dream memory maintenance for this workspace.",
    "",
    "Execution bounds:",
    "- Only modify `notes/daily/` and `notes/memory/` files.",
    "- Do not modify project code, tests, runtime sources, or unrelated config.",
    "- Load memory at session start from `notes/memory/MEMORY.md` and `notes/index.md`, then open deeper files only as needed.",
    "- Your tool access is intentionally constrained for Dream reliability; prefer the smallest number of reads/searches needed to finish the pass.",
    "",
    "You are the evaluator for what is relevant. Do not use fixed message-length heuristics; use judgment based on the recent evidence you inspect.",
    "",
    "Follow the original 4-phase Dream flow:",
    "1. Orient:",
    "- Runtime has already created a pre-Dream backup and refreshed/seeded daily note files from all chats in scope before you start editing (excluding temporary `dream:` chats).",
    "- Any daily note still containing `<!-- NEEDS_SUMMARY -->` or `<!-- NEEDS_SUMMARY_UPDATE -->` is unfinished and must be treated as needing consolidation, not as a completed day.",
    "- Any note with the visible '⚠ Incomplete daily note' warning block is provisional; remove that warning only after you have fully consolidated the day and updated `summarised_until` truthfully.",
    "- Load startup memory from `notes/memory/MEMORY.md` and `notes/index.md`.",
    "- Inspect relevant `notes/daily/*.md` and existing `notes/memory/*` files before deciding what matters.",
    "- Treat daily-note front matter as the deterministic transcript contract: `scope_anchor`, `first_message`, `last_message`, `messages_total`, `session_trees`, and `session_chats` define the bounded evidence slice for that note.",
    "- Unfinished notes may contain hidden `DREAM_CUES` comments. Use those cue terms/snippets first; for small bounded days (`messages_total <= 50` and `session_trees <= 2`), it is acceptable to inspect the full bounded day slice before declaring consolidation unsafe.",
    "- Open deeper files only when they are needed to resolve uncertainty.",
    "2. Signal:",
    "- Look for new information worth persisting.",
    "- Prioritize the daily notes already seeded for this window, then memories that drifted from reality, then narrow transcript/message confirmation only when needed.",
    "- Use rough/narrow searches, not exhaustive transcript reading.",
    "- Only if you need specific confirmation, use narrow `messages.search` queries for terms you already suspect matter, bounded by the front-matter `first_message`/`last_message` range where possible.",
    "- Do not sweep the whole transcript history blindly.",
    "3. Consolidate:",
    "- Merge new signal into existing note/memory files instead of creating near-duplicates.",
    "- Convert phrases like 'today' or 'yesterday' into absolute dates.",
    "- If a newer fact disproves an older memory, fix the older source file.",
    "- Update the `## Summary` section for each daily note in scope so it reflects the final understanding for that day.",
    "- Explicitly replace `<!-- NEEDS_SUMMARY -->` and `<!-- NEEDS_SUMMARY_UPDATE -->` markers for in-scope days once you have enough evidence; do not leave placeholder markers behind accidentally.",
    "- For partially summarised days, keep the Summary update flow coherent and advance `summarised_until` to the day's `last_message` when the note is fully brought up to date.",
    "- When you finish consolidating a once-partial note, remove the visible incomplete-note warning block as part of the same edit so the prose and metadata agree.",
    "- Never leave a finalized prose `## Summary` with blank `summarised_until`; either set `summarised_until` to that note's `last_message` when fully consolidated, or keep the incomplete marker/warning and explain the unresolved date.",
    "- Keep `notes/daily/` and `notes/memory/` aligned as two layers of the same final state.",
    "4. Prune and Index:",
    "- Remove obsolete pointers, redundant notes, and index entries that no longer help.",
    "- Add pointers to newly important memories that future sessions should be able to find quickly.",
    "- Keep `notes/memory/MEMORY.md` compact, one-line-per-entry, and under the startup budget.",
    "- If an index line is overly verbose, shorten it and move the detail into the linked memory file instead of carrying content in the index.",
    "- The runtime will refresh workspace FTS indexing after your Dream pass completes; you do not need to perform infrastructure housekeeping yourself.",
    "",
    `Window: focus on the last ${days} day(s).`,
    "",
    "Required outputs:",
    "- Keep `notes/daily/` as the concise human-readable overview layer.",
    "- Keep `notes/memory/` as the durable agent-memory layer.",
    "- Keep `notes/memory/MEMORY.md` as an index only: compact, one-line entries, and under the startup budget.",
    "- Update typed memory files (`user.md`, `feedback.md`, `project.md`, `reference.md`) only if the new signal actually changes them.",
    "- Keep `notes/memory/current-state.md` and `notes/memory/recent-context.md` aligned with your final consolidated state.",
    "- Treat `notes/memory/days/*.md` as optional sparse episodic memory: create, update, or prune them only when a day carries durable agent-facing signal beyond the human-readable daily note.",
    "- Do not create or depend on JSON sidecars; keep durable Dream memory surfaces in Markdown.",
    "- Keep daily-note front matter truthful, especially `summarised_until`, `first_message`, and `last_message` when you touch a note.",
    "- A day is not done while either summary placeholder marker is still present in its note; only leave a marker if the note truly remains incomplete after your narrow evidence-gathering pass.",
    "- If a day remains incomplete, mention the unresolved date and why in your final Dream summary so runtime post-processing can surface it clearly.",
    "",
    "Return a brief summary of what changed across Orient, Signal, Consolidate, and Prune and Index, plus whether runtime post-processing succeeded.",
  ].join("\n");
}
